name: linting, testing, building
run-name: ${{ github.event.head_commit.message }} 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v5

      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build:prod
        if: always()
      - name: Eslint
        run: |
          npm run lint
        if: always()
      - name: Stylelint
        run: |
          npm run lint:scss
        if: always()
      - name: Unit testing
        run: |
          npm run unit
        if: always()
      - name: Storybook
        run: |
          npm run storybook:build
